# 1- Applying logistic regression and SVM


## scikit-learn refresher

In [1]:
# from sklearn.neighbors import KNeighborsClassifier

# # Create and fit the model
# knn = KNeighborsClassifier()
# knn.fit(X_train, y_train)

# # Predict on the test features, print the results
# pred = knn.predict(X_test)[0]
# print("Prediction for test example 0:", pred)

## Applying logistic regression and SVM


In [2]:
from sklearn.datasets import load_wine
X, y = load_wine(return_X_y=True)

from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X,y)
print(lr.score(X, y))

0.9662921348314607


c:\program files\python38\lib\site-packages\sklearn\linear_model\_logistic.py:938: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [3]:
lr.predict_proba(X[:1])
# e = 10^ num
# 9.95e-1 = 0.99 = 99%

array([[9.96582894e-01, 2.73866353e-03, 6.78442429e-04]])

* Underfitting: model is too simple, low traning accuracy

* Overfitting: model is too complex, low test accuracy

In [4]:
# from sklearn import datasets
# digits = datasets.load_digits()
# X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target)

# # Apply logistic regression and print scores
# lr = LogisticRegression()
# lr.fit(X_train, y_train)
# print(lr.score(X_train,y_train))
# print(lr.score(X_test,y_test))

# # Apply SVM and print scores
# svm = SVC()
# svm.fit(X_train, y_train)
# print(svm.score(X_train,y_train))
# print(svm.score(X_test,y_test))


In [5]:
# # Instantiate logistic regression and train
# lr = LogisticRegression()
# lr.fit(X, y)

# # Predict sentiment for a glowing review
# review1 = "I love all muslims in the world so much"
# review1_features = get_features(review1)
# print("Review:", review1)
# print("Probability of positive review:", lr.predict_proba(review1_features)[0,1])

# # Predict sentiment for a poor review
# review2 = "I hate the Israel people"
# review2_features = get_features(review2)
# print("Review:", review2)
# print("Probability of positive review:", lr.predict_proba(review2_features)[0,1])

## Linear classifiers


![alt text](AditionalResources/1.png "k-means clustering with scikit-learn")

![alt text](AditionalResources/2.png "k-means clustering with scikit-learn")

![alt text](AditionalResources/3.png "k-means clustering with scikit-learn")

In [6]:
# from sklearn.linear_model import LogisticRegression
# from sklearn.svm import SVC, LinearSVC
# from sklearn.neighbors import KNeighborsClassifier

# # Define the classifiers
# classifiers = [LogisticRegression(), LinearSVC(), SVC(), KNeighborsClassifier()]

# # Fit the classifiers
# for c in classifiers:
#     c.fit(X, y)

# # Plot the classifiers
# plot_4_classifiers(X, y, classifiers)
# plt.show()


![alt text](AditionalResources/4.png "k-means clustering with scikit-learn")

# 2- Loss functions


## Linear classifiers: the coefficients


In [7]:
import numpy as np
X = np.arange(3)
X

array([0, 1, 2])

In [8]:
y = np.arange(3,6)
y

array([3, 4, 5])

In [9]:
X*y

array([ 0,  4, 10])

In [10]:
np.sum(X*y)

14

In [11]:
X@y # dot product

14

![alt text](AditionalResources/5.png "k-means clustering with scikit-learn")

![alt text](AditionalResources/6.png "k-means clustering with scikit-learn")

![alt text](AditionalResources/7.png "k-means clustering with scikit-learn")

## What is a loss function?


![alt text](AditionalResources/8.png "k-means clustering with scikit-learn")

![alt text](AditionalResources/9.png "k-means clustering with scikit-learn")

In [12]:
# # The squared error, summed over training examples
# def my_loss(w):
#     s = 0
#     for i in range(y.size):
#         # Get the true and predicted target values for example 'i'
#         y_i_true = y[i]
#         y_i_pred = w@X[i]
#         s = s + (y_i_true - y_i_pred)**2
#     return s

# # Returns the w that makes my_loss(w) smallest
# w_fit = minimize(my_loss, X[0]).x
# print(w_fit)

# # Compare with scikit-learn's LinearRegression coefficients
# lr = LinearRegression(fit_intercept=False).fit(X,y)
# print(lr.coef_)


## Loss function diagrams


In [13]:
# # Mathematical functions for logistic and hinge losses
# def log_loss(raw_model_output):
#    return np.log(1+np.exp(-raw_model_output))
# def hinge_loss(raw_model_output):
#    return np.maximum(0,1-raw_model_output)

# # Create a grid of values and plot
# grid = np.linspace(-2,2,1000)
# plt.plot(grid, log_loss(grid), label='logistic')
# plt.plot(grid, hinge_loss(grid), label='hinge')
# plt.legend()
# plt.show()

In [14]:
# # The logistic loss, summed over training examples
# def my_loss(w):
#     s = 0
#     for i in range(y.size):
#         raw_model_output = w@X[i]
#         s = s + log_loss(raw_model_output * y[i])
#     return s

# # Returns the w that makes my_loss(w) smallest
# w_fit = minimize(my_loss, X[0]).x
# print(w_fit)

# # Compare with scikit-learn's LogisticRegression
# lr = LogisticRegression(fit_intercept=False, C=1000000).fit(X,y)
# print(lr.coef_)


# 3- Logistic regression


## Logistic regression and regularization


![alt text](AditionalResources/10.png "k-means clustering with scikit-learn")

![alt text](AditionalResources/11.png "k-means clustering with scikit-learn")

![alt text](AditionalResources/12.png "k-means clustering with scikit-learn")

![alt text](AditionalResources/14.png "k-means clustering with scikit-learn")

![alt text](AditionalResources/15.png "k-means clustering with scikit-learn")

In [15]:
# # Train and validaton errors initialized as empty list
# train_errs = list()
# valid_errs = list()

# # Loop over values of C_value
# for C_value in [0.001, 0.01, 0.1, 1, 10, 100, 1000]:
#     # Create LogisticRegression object and fit
#     lr = LogisticRegression(C=C_value)
#     lr.fit(X_train, y_train)
    
#     # Evaluate error rates and append to lists
#     train_errs.append( 1.0 - lr.score(X_train, y_train) )
#     valid_errs.append( 1.0 - lr.score(X_valid, y_valid) )
    
# # Plot results
# plt.semilogx(C_values, train_errs, C_values, valid_errs)
# plt.legend(("train", "validation"))
# plt.show()

![alt text](AditionalResources/16.png "k-means clustering with scikit-learn")

In [16]:
# # Specify L1 regularization
# lr = LogisticRegression(penalty='l1')

# # Instantiate the GridSearchCV object and run the search
# searcher = GridSearchCV(lr, {'C':[0.001, 0.01, 0.1, 1, 10]})
# searcher.fit(X_train, y_train)

# # Report the best parameters
# print("Best CV params", searcher.best_params_)

# # Find the number of nonzero coefficients (selected features)
# best_lr = searcher.best_estimator_
# coefs = best_lr.coef_
# print("Total number of features:", coefs.size)
# print("Number of selected features:", np.count_nonzero(coefs))

In [17]:
# # Get the indices of the sorted cofficients
# inds_ascending = np.argsort(lr.coef_.flatten()) 
# inds_descending = inds_ascending[::-1]

# # Print the most positive words
# print("Most positive words: ", end="")
# for i in range(5):
#     print(vocab[inds_descending[i]], end=", ")
# print("\n")

# # Print most negative words
# print("Most negative words: ", end="")
# for i in range(5):
#     print(vocab[inds_ascending[i]], end=", ")
# print("\n")

## Logistic regression and probabilities


![alt text](AditionalResources/17.png "k-means clustering with scikit-learn")

![alt text](AditionalResources/18.png "k-means clustering with scikit-learn")

In [18]:
# # Set the regularization strength , large C
# model = LogisticRegression(C=1)

# # Fit and plot
# model.fit(X,y)
# plot_classifier(X,y,model,proba=True)

# # Predict probabilities on training points
# prob = model.predict_proba(X)
# print("Maximum predicted probability", np.max(prob))

![alt text](AditionalResources/19.png "k-means clustering with scikit-learn")

In [19]:
# # Set the regularization strength, small C
# model = LogisticRegression(C=0.1)

# # Fit and plot
# model.fit(X,y)
# plot_classifier(X,y,model,proba=True)

# # Predict probabilities on training points
# prob = model.predict_proba(X)
# print("Maximum predicted probability", np.max(prob))

![alt text](AditionalResources/20.png "k-means clustering with scikit-learn")

In [20]:
# lr = LogisticRegression()
# lr.fit(X,y)

# # Get predicted probabilities
# proba = lr.predict_proba(X)

# # Sort the example indices by their maximum probability
# proba_inds = np.argsort(np.max(proba,axis=1))

# # Show the most confident (least ambiguous) digit
# show_digit(proba_inds[-1], lr)

# # Show the least confident (most ambiguous) digit
# show_digit(proba_inds[0], lr)

## Multi-class logistic regression


![alt text](AditionalResources/21.png "k-means clustering with scikit-learn")

![alt text](AditionalResources/22.png "k-means clustering with scikit-learn")

In [21]:
# Fit one-vs-rest logistic regression classifier
# lr_ovr = LogisticRegression()
# lr_ovr.fit(X_train, y_train)

# print("OVR training accuracy:", lr_ovr.score(X_train, y_train))
# print("OVR test accuracy    :", lr_ovr.score(X_test, y_test))

# # Fit softmax classifier
# lr_mn = LogisticRegression(multi_class='multinomial', solver='lbfgs')
# lr_mn.fit(X_train, y_train)

# print("Softmax training accuracy:", lr_mn.score(X_train, y_train))
# print("Softmax test accuracy    :", lr_mn.score(X_test, y_test))

#     OVR training accuracy: 0.9948032665181886
#     OVR test accuracy    : 0.9644444444444444
#     Softmax training accuracy: 1.0
#     Softmax test accuracy    : 0.9688888888888889
        

In [22]:
# # Print training accuracies
# print("Softmax     training accuracy:", lr_mn.score(X_train, y_train))
# print("One-vs-rest training accuracy:", lr_ovr.score(X_train, y_train))

# # Create the binary classifier (class 1 vs. rest)
# lr_class_1 = LogisticRegression(C=100)
# lr_class_1.fit(X_train, y_train==1)

# # Plot the binary classifier (class 1 vs. rest)
# plot_classifier(X_train, y_train==1, lr_class_1)

# Softmax     training accuracy: 0.996
# One-vs-rest training accuracy: 0.916


![alt text](AditionalResources/23.png "k-means clustering with scikit-learn")

In [23]:
# # We'll use SVC instead of LinearSVC from now on
# from sklearn.svm import SVC

# # Create/plot the binary classifier (class 1 vs. rest)
# svm_class_1 = SVC()
# svm_class_1.fit(X_train, y_train==1)
# plot_classifier(X_train, y_train==1, svm_class_1)



![alt text](AditionalResources/24.png "k-means clustering with scikit-learn")

## 4- Support vectors


In [24]:
# # Train a linear SVM
# svm = SVC(kernel="linear")
# svm.fit(X, y)
# plot_classifier(X, y, svm, lims=(11,15,0,6))

# # Make a new data set keeping only the support vectors
# print("Number of original examples", len(X))
# print("Number of support vectors", len(svm.support_))
# X_small = X[svm.support_]
# y_small = y[svm.support_]

# # Train a new SVM using only the support vectors
# svm_small = SVC(kernel="linear")
# svm_small.fit(X, y)
# plot_classifier(X_small, y_small, svm_small, lims=(11,15,0,6))


![alt text](AditionalResources/25.png "k-means clustering with scikit-learn")

## Kernel SVMs


![alt text](AditionalResources/26.png "k-means clustering with scikit-learn")

![alt text](AditionalResources/27.png "k-means clustering with scikit-learn")

![alt text](AditionalResources/28.png "k-means clustering with scikit-learn")

In [25]:
# # Instantiate an RBF SVM
# svm = SVC() # defult kernel='rbf'

# # Instantiate the GridSearchCV object and run the search
# parameters = {'gamma':[0.00001, 0.0001, 0.001, 0.01, 0.1]}
# searcher = GridSearchCV(svm, parameters)
# searcher.fit(X, y)

# # Report the best parameters
# print("Best CV params", searcher.best_params_)

# Best CV params {'gamma': 0.001}

In [26]:
# # Instantiate an RBF SVM
# svm = SVC()

# # Instantiate the GridSearchCV object and run the search
# parameters = {'C':[0.1, 1, 10], 'gamma':[0.00001, 0.0001, 0.001, 0.01, 0.1]}
# searcher = GridSearchCV(svm, parameters)
# searcher.fit(X_train, y_train)

# # Report the best parameters and the corresponding score
# print("Best CV params", searcher.best_params_)
# print("Best CV accuracy", searcher.best_score_)

# # Report the test accuracy using these best parameters
# print("Test accuracy of best grid search hypers:", searcher.score(X_test, y_test))

# Best CV params {'C': 10, 'gamma': 0.0001}
# Best CV accuracy 0.9955481357818586
# Test accuracy of best grid search hypers: 1.0


![alt text](AditionalResources/29.png "k-means clustering with scikit-learn")

![alt text](AditionalResources/30.png "k-means clustering with scikit-learn")

![alt text](AditionalResources/31.png "k-means clustering with scikit-learn")

## Comparing logistic regression and SVM (and beyond)


![alt text](AditionalResources/32.png "k-means clustering with scikit-learn")

![alt text](AditionalResources/33.png "k-means clustering with scikit-learn")

![alt text](AditionalResources/34.png "k-means clustering with scikit-learn")

![alt text](AditionalResources/35.png "k-means clustering with scikit-learn")

In [27]:
# # We set random_state=0 for reproducibility 
# linear_classifier = SGDClassifier(random_state=0)

# # Instantiate the GridSearchCV object and run the search
# parameters = {'alpha':[0.00001, 0.0001, 0.001, 0.01, 0.1, 1], 
#              'loss':['hinge', 'log'], 'penalty':['l1','l2']}
# searcher = GridSearchCV(linear_classifier, parameters, cv=10)
# searcher.fit(X_train, y_train)

# # Report the best parameters and the corresponding score
# print("Best CV params", searcher.best_params_)
# print("Best CV accuracy", searcher.best_score_)
# print("Test accuracy of best grid search hypers:", searcher.score(X_test, y_test))

# Best CV params {'alpha': 0.0001, 'loss': 'hinge', 'penalty': 'L1'}
# Best CV accuracy 0.94351630867144
# Test accuracy of best grid search hypers: 0.9592592592592593
    
    